version: '3.1'

services:
  mae:
    container_name: app
    image: mae/app
    build:
      # image: mae/app
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    # Permit communication with the host docker server
    # volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    networks:
      - mae_net
    environment:
      - RUN_TWO="1"


  mysql:
    container_name: mysql
    image: mariadb:10.5.8
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/tmp/init.sql
    networks:
      - mae_net
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

networks:
  mae_net:
